{ inputs }:

# =============================================================================
# lib/mkHost.nix — Фабрика хоста
# =============================================================================
# Принимает имя папки в hosts/, возвращает nixosSystem.
#
# Структура hosts/<имя>/:
#   settings.nix   — параметры машины (обязательно)
#   hardware.nix   — generated by nixos-generate-config (обязательно)
#   default.nix    — entry-point модулей кастомизации (опционально, v0.5.0+)
#   packages.nix   — пакеты, импортированные из default.nix (опционально)
#   ... и любые другие .nix модули которые подключены через default.nix
#   dotfiles/      — декларативные dotfile overrides (опционально, v0.5.0+)
#
# В v0.5.0 папка custom/ упразднена — всё что было в custom/<host>.nix или
# custom/<host>/ теперь живёт прямо в hosts/<host>/.
# =============================================================================

{ name }:

let
  inherit (inputs) nixpkgs home-manager disko catppuccin sops-nix;
  lib = nixpkgs.lib;

  hostPath = ../hosts + "/${name}";
  settings = import (hostPath + "/settings.nix");

  # ── Кастомизации этой машины: hosts/<host>/default.nix (v0.5.0+) ──────────
  # default.nix импортирует через свой `imports` остальные .nix модули
  # которые лежат рядом — packages.nix, services.nix, и т.д. То есть mkHost
  # подключает только default.nix; полный граф кастомизации описан в нём.
  hostDefault = hostPath + "/default.nix";
  customModule =
    if builtins.pathExists hostDefault
    then [ (import hostDefault) ]
    else [];

  # ── Conditional modules: выбор по settings ───────────────────────────────
  cpuModule = {
    "amd"   = ../modules/system/hardware/cpu-amd.nix;
    "intel" = ../modules/system/hardware/cpu-intel.nix;
  }.${settings.cpu} or (throw "settings.cpu: ожидалось amd|intel, получено «${settings.cpu}»");

  gpuModule = {
    "amd"    = ../modules/system/hardware/gpu-amd.nix;
    "intel"  = ../modules/system/hardware/gpu-intel.nix;
    "nvidia" = ../modules/system/hardware/gpu-nvidia.nix;
  }.${settings.gpu} or (throw "settings.gpu: ожидалось amd|intel|nvidia, получено «${settings.gpu}»");

  profileModule = {
    "laptop"  = ../modules/system/profiles/laptop.nix;
    "desktop" = ../modules/system/profiles/desktop.nix;
    "server"  = ../modules/system/profiles/server.nix;
  }.${settings.profile} or (throw "settings.profile: ожидалось laptop|desktop|server, получено «${settings.profile}»");

  diskoModule = {
    "wipe"     = ../modules/disko/btrfs.nix;
    "existing" = ../modules/disko/btrfs-existing.nix;
  }.${settings.diskMode} or (throw "settings.diskMode: ожидалось wipe|existing, получено «${settings.diskMode}»");

  # ── Автодискавер модулей ──────────────────────────────────────────────────
  # Берём все *.nix файлы из указанных путей (на одном уровне, без рекурсии
  # в подпапки — потому что hardware/profiles/ это conditional choice, их
  # автоматом включать нельзя).
  # Файлы начинающиеся с _ игнорируются (зарезервировано для шаблонов).
  collectNixFiles = path:
    let entries = builtins.readDir path;
    in lib.pipe entries [
      (lib.filterAttrs (n: t:
        t == "regular"
        && lib.hasSuffix ".nix" n
        && !lib.hasPrefix "_" n))
      (lib.mapAttrsToList (n: _: path + "/${n}"))
    ];

  autoDiscoverPaths = [
    ../modules/system           # boot, network, locale, users, base, nix, variables, power-profiles, bootstrap
    ../modules/system/services  # printing, bluetooth
    ../modules/system/ui        # audio, fonts, session
  ];

  autoModules = lib.concatMap collectNixFiles autoDiscoverPaths;
in
nixpkgs.lib.nixosSystem {
  system      = "x86_64-linux";
  specialArgs = { inherit inputs settings; hostName = name; };

  modules = [
    # ── Разметка диска ──────────────────────────────────────────────────
    disko.nixosModules.disko
    diskoModule

    # ── Catppuccin (системный уровень — консоль, plymouth и т.д.) ───────
    catppuccin.nixosModules.catppuccin

    # ── Секреты (sops-nix, v0.3.0) ──────────────────────────────────────
    # Активируется через настройку modules/system/sops.nix; если secrets/
    # пустая — модуль no-op.
    sops-nix.nixosModules.sops

    # ── Железо конкретной машины ────────────────────────────────────────
    (hostPath + "/hardware.nix")

    # ── Conditional choice modules ──────────────────────────────────────
    cpuModule
    gpuModule
    profileModule

    # ── Home Manager ────────────────────────────────────────────────────
    home-manager.nixosModules.home-manager
    {
      home-manager.useGlobalPkgs    = true;
      home-manager.useUserPackages  = true;
      home-manager.extraSpecialArgs = { inherit inputs settings; hostName = name; };
      home-manager.sharedModules    = [ catppuccin.homeModules.catppuccin ];
      home-manager.users.${settings.username} = import ../modules/user/home.nix;
    }
  ]
  ++ autoModules         # boot/network/locale/users/base/nix/variables/power-profiles/bootstrap + services/* + ui/*
  ++ customModule;       # hosts/<host>/default.nix (если есть)
}
