# =============================================================================
# general.conf — Общие настройки compositor
# =============================================================================

general {
    gaps_in     = 4         # отступы между окнами
    gaps_out    = 8         # отступы от краёв экрана
    border_size = 2
    layout      = dwindle   # двухпанельный layout с автоделением

    # Цвета бордеров — переопределяются catppuccin-nix автоматически
    # col.active_border   = ...
    # col.inactive_border = ...

    resize_on_border  = true
    allow_tearing     = false
}

dwindle {
    pseudotile     = true   # окна в плавающем режиме сохраняют размер
    preserve_split = true
}

master {
    new_status = master
}
