# =============================================================================
# misc.conf — Прочее: лого, splash, поведение
# =============================================================================

misc {
    disable_hyprland_logo    = true   # без вотермарки
    disable_splash_rendering = true   # без splash при старте
    force_default_wallpaper  = 0      # 0=отключено, обои через hyprpaper
    vfr                      = true   # variable refresh rate — экономия энергии
}

# XWayland scaling — для совместимости с X11 приложениями
xwayland {
    force_zero_scaling = true
}
