# =============================================================================
# decoration.conf — Скругления, размытие, тени
# =============================================================================

decoration {
    rounding = 8

    blur {
        enabled       = true
        size          = 3
        passes        = 1
        new_optimizations = true
    }

    shadow {
        enabled      = true
        range        = 4
        render_power = 3
    }

    # Прозрачность окон по умолчанию
    active_opacity   = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
}
