# hyprpaper.conf — Обои
# Положи свои обои в ~/Pictures/wallpaper.png или укажи другой путь.
# Несколько мониторов: указывай каждый через preload + wallpaper.

preload   = ~/Pictures/wallpaper.png
wallpaper = ,~/Pictures/wallpaper.png

splash = false
